#pragma once
enum GameState {
    START_SCREEN,
    MAIN_MENU,
    PLAYING,
    PAUSED,
    GAME_OVER,
    LOGIN_SCREEN,
    REGISTER_SCREEN,
    LEADERBOARD_SCREEN,
    PROFILE_SCREEN,
    SAVE_GAME_SCREEN,  
    LOAD_GAME_SCREEN,
    ACCOUNT_SCREEN,
    PLAYER_MENU,
    INVENTORY_SCREEN,
    MULTIPLAYER_MENU
};
